name: deploy

on:
  push:
    branches:
      - master


jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: ssh to ec2
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USER }} 
          script: |
            PID=$(lsof -t -i:8081)
            if [ -z "$PID" ]; then
              echo "No process is running on port 8081"
            else
              echo "Killing process $PID"
              kill -9 $PID
            fi
            cd 5c0_server
            git pull origin master
            sh gradlew build
            cd build/libs
            nohup java -jar wllserver-0.0.1-SNAPSHOT.jar > ~/5c0_server/nohup.out 2>&1 &
